### PR TITLE
Updates for compatibility with recent Hy changes

### PR DESCRIPTION
**Pull request by brandonwillard**
XXX: There appear to be breaking changes in how reader/tags are used in this
library and parsed/lexed by Hy.  

From what I can tell, tags can't take empty arguments: e.g.  `(print #s)` fails &mdash; apparently because `)` is parsed as an argument to `#s` &mdash; where `(print #s None)` doesn't.

@algernon, any ideas on how best to handle this?

### CODE REVIEW

**Comment by algernon** [comment]
> From what I can tell, tags can't take empty arguments: e.g. `(print #s)` fails — apparently because `)` is parsed as an argument to `#s` — where `(print #s None)` doesn't.

That's why the code used `#ss` and `#uu` all around the place, while defining the reader macros as `s` and `u` only. I guess the same could work now, too?

**Comment by brandonwillard** [comment]
Looks like Hy doesn't like `#ss`; it assumes it's a different tag macro (i.e. non-single character tag name).

**Comment by algernon** [comment]
Not sure how to best solve it then, save for modifying Hy itself to accept argument-less tags... or using `succeed` and `fail` directly, making the code more verbose, and... ugly. :/

**Comment by brandonwillard** [comment]
Yeah, that's exactly what I was thinking.

Seems like the changes required to make `#ss` work (again) would complicate things (e.g. prefer `#ss` parsed as `#s s` over `#ss nil` when `#ss` is a defined macro), so argument-less tags is most likely the correct approach.  

Regardless, I would prefer to make tags work for this, but, to move forward, `succeed` and `fail` is fine.

Created hylang/hy#1642 to ask about argument-less tag macros.

**Comment by brandonwillard** [comment]
Also, I noticed that [core.logic](https://github.com/clojure/core.logic/blob/master/src/main/clojure/clojure/core/logic.clj#L1148) uses aliases `s#` and `u#`; that could be a little better.

**Comment by brandonwillard** [comment]
Need to get https://github.com/algernon/monaxhyd/pull/2 working to move forward.

**Comment by brandonwillard** [comment]
@algernon, see the commit message for https://github.com/algernon/adderall/pull/8/commits/4722d1a7d4929604386f9d55d7446affeed8fb97; there are some design/logic changes &mdash; mostly involving the `cons` removal &mdash; that might require an alternative approach to implementing miniKanren.  

You know, the lack of `cons` makes me think of [logpy/kanren](https://github.com/logpy/logpy), which sufficiently works around it, so it's definitely doable.

Also, I renamed the branch to [recent-hy-updates](https://github.com/brandonwillard/adderall/tree/recent-hy-updates), but that doesn't seem to affect the associated Github PR.  Should I just close this one and open a new one?

**Comment by algernon** [comment]
> Should I just close this one and open a new one?

Yes, please.

(I'll try to comment on the rest tomorrow)

**Pull request closed without merging**
