### PR TITLE
Updates for compatibility with recent Hy changes

### PR DESCRIPTION
**Pull request by brandonwillard**
This PR renames/replaces https://github.com/algernon/adderall/pull/8..

### CODE REVIEW

**Comment by brandonwillard** [comment]
The current issue(s) can be demonstrated by the following:
```clojure
(fresh [x] 
  (≡ x 2)
  (project [x] 
    (≡ q (type x))))
```
Attempting to evaluate this (whether in a `run` or not) yields the error message `HyMacroExpansionError: bind targets must be symbols`.

Expanded, the above is (after removing "_;" prefix from symbol names)
```clojure
(do
  (setv let|1319 {}
        (get let|1319 "x") (LVar (gensym 'x)))
  (all (≡ (get let|1319 "x") 2)
       (fn [s|1320]
         (do
           (require [hy.contrib.walk [let :as let|1321]])
           (let|1321 [__x (get let|1319 "x")
                           (get let|1319 "x") (reify __x s|1320)]
                     ((all (≡ q (type (get let|1319 "x"))))
                      s|1320))))))
```
where the relevant line is 
```clojure
           (let|1321 [__x (get let|1319 "x")
                           (get let|1319 "x") (reify __x s|1320)]
```

I'm assuming that `let` does not evaluate the variables to be bound when they're expressions, so we might need to do that ourselves.

**Comment by brandonwillard** [comment]
I think the root problem has to do with macro expansion and the use of `require` within macros.

Consider the following:
```clojure
(require [hy.contrib.walk [let]])

(defmacro fresh-good [a b]
  `(do (let [~a 1] ~b)))

(defmacro/g! fresh-bad [a b]
  `(do
     (require [hy.contrib.walk [let :as ~g!let]])
     (~g!let [~a 1] ~b)))

(defmacro project-good [y]
  `(do (let [~y 2] ~y)))

(defmacro/g! project-bad [y]
  `(do
     (require [hy.contrib.walk [let :as ~g!let]])
     (~g!let [~y 2] ~y)))
```
The functions labeled `-bad` are an extremely distilled version of the problem [above](https://github.com/algernon/adderall/pull/9#issuecomment-403528702).  

Evaluating them analogous to how we would above, we can confirm that the output also corresponds:
```clojure
;; Reference case
=> (fresh-good a (project-good a))
_hyx_XsemicolonXletXvertical_lineX1665 = {}
_hyx_XsemicolonXletXvertical_lineX1665['a'] = 1
_hyx_XsemicolonXletXvertical_lineX1666 = {}
_hyx_XsemicolonXletXvertical_lineX1666['a'] = 2
_hyx_XsemicolonXletXvertical_lineX1666['a']

2

;; Direct correspondence case
=> (fresh-bad a (project-bad a))
File "<input>", unknown location
HyMacroExpansionError: bind targets must be symbols

;; Test case 1
=> (fresh-bad a (project-good a))
_hyx_XsemicolonXletXvertical_lineX1762 = {}
_hyx_XsemicolonXletXvertical_lineX1762['a'] = 1
_hyx_XsemicolonXletXvertical_lineX1763 = {}
_hyx_XsemicolonXletXvertical_lineX1763['a'] = 2
_hyx_XsemicolonXletXvertical_lineX1763['a']

2

;; Test case 2
=> (fresh-good a (project-bad a))
File "<input>", unknown location
HyMacroExpansionError: bind targets must be symbols
```
These examples hint toward the inner `require` (i.e. `-bad`) macro being the cause of the problem.

Since `let` expands (using `macroexpand-all`) the macros of its `body` argument and replaces its `bindings` keys &mdash; which are symbols &mdash; with `get` expressions to the `let`-bindings env/dictionary it generates, the expression `(fresh-good a (project-bad a))` performs the naive replacement in the unexpanded inner `gensym`ed `let` form, which then leads to a malformed `let`.  The replacement is only possible because the inner `let` hasn't been expanded by the outer `let`'s call to `macroexpand-all`, as this would've otherwise replaced all occurrences of `HySymbol("a")`.  The only time the inner `let` is expand is during evaluation, but then it's already a malformed `let` without the possibility of our intervention.

Besides reverting the use of `require` within the macros, I can't think of a particularly good fix right now.  I've tried forcing expansion of the `require`ed  `let` in `project-bad`, but that seems to necessitate supplementary `eval` logic elsewhere.  Functionality like [`cl-letf`](https://github.com/hylang/hy/issues/1660#issue-340496878) would handle this particular case, but perhaps not much else.  It might also be possible to extend the considerations of `hy.contrib.walk.SymbolExpander`, so that it expands aliased `gensym`ed symbols corresponding to macro `require`s.
I've probably missed something simpler, but, as of now, this is where I'm at with the problem.

**Comment by gilch** [comment]
From your description, I think the problem is that `macroexpand-all` is still not meeting the spec I described in https://github.com/hylang/hy/issues/1420.

It probably needs to handle `require` and `eval-and-compile`/`eval-when-compile` specially.

**Comment by brandonwillard** [comment]
@gilch, just put in a PR for this functionality: https://github.com/hylang/hy/pull/1664

**Comment by brandonwillard** [comment]
All right, all the tests should pass now, but I had to enforce a stricter use of `cons`.
I'm not sure if that clashes with the desired semantics and compatibility with Hy/Python, but it's definitely not hard to use and it lines up well with all the miniKanren work in Scheme.

**Comment by brandonwillard** [comment]
Updated the `bench` tests.

The remaining Travis failures are for versions of Python no longer supported by Hy; @algernon, should we remove those versions and add Pythons 3.5, 3.6, 3.7?

**Comment by algernon** [comment]
Thank you for the incredible amount of work you put in this! <3

**Comment by brandonwillard** [comment]
@algernon, anytime!  

I'll take a crack at updating [hydiomatic](https://github.com/hylang/hydiomatic) next, then the basics of some symbolic math and proof assistant/type theory capabilities via miniKanren (in Hy, using this project, of course).  Ultimately, I plan to work Theano (and maybe SymPy) into the mix.

If you're interested, I can provide more details (Gitter, IRC?); regardless, would gladly have your input on these follow-up projects.

**Comment by brandonwillard** [comment]
@algernon, I can help with managerial things, if you'd like.  

Personally, I think miniKanren-like concepts and DSLs are &mdash; and will be &mdash; sorely needed in certain areas of work, and a project like this (through Hy) is a much better approach than shoe-horning miniKanren and/or Python.  That said, I'm convinced this project is well worth maintaining.

Also, I had wondered why `hydiomatic` was under `hylang/` and this wasn't.

**Comment by brandonwillard** [comment]
What's the deal with [that Travis failure](https://travis-ci.org/algernon/adderall/jobs/422944290)?  That `pypy3.5` archive download URL seems valid.  Just an AWS hiccup?

**Pull request merged**
